# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d951ca6effc438e345be815b65dc0fa4b9def3713e07fe0cd7e21d973e3d7c8e90069e99103921405cab20866b878907eebd6d68b717dbba2d5f37a6da401a0f

test:
  secret_key_base: a137760298a9dbb80a5095bc491beb44fadc5c67fa5fdffa7f2ef3ff44d997b3a504d2ab0c5316e32266f9fd3fc58b6225577f4a772c1154cc6cab5f3c72312f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
